# Generated by Django 5.0.3 on 2024-03-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sentiment",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
