# Generated by Django 5.0.3 on 2024-03-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
